defmodule RenderingExamples do
  @moduledoc """
  Writes `examples/rendering.txt`: the formulas below, each with what
  `LatexUnicode.render/2` returns for it, so the file can be read back in a terminal.

      mix run examples/render.exs
      cat examples/rendering.txt

  The file is generated, not written by hand — rerunning the script after a change and
  diffing it is how it stays honest:

      mix run examples/render.exs && git diff --exit-code examples/rendering.txt
  """

  @width 78

  @sections [
    {
      "Inline math",
      "One line, pi's rendering: fractions and limits collapse into the text.",
      [],
      [
        "\\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}",
        "x^2 + y^2 = r^2",
        "e^{i\\pi} + 1 = 0",
        "\\sum_{i=1}^{n} i = \\frac{n(n+1)}{2}",
        "\\hat{H}\\psi = E\\psi",
        "\\vec{v} \\cdot \\vec{w} = |\\vec{v}|\\,|\\vec{w}|\\cos\\theta",
        "\\alpha + \\beta \\to \\gamma \\quad (\\varepsilon > 0)",
        "\\lim_{x \\to \\infty} \\frac{1}{x} = 0",
        "\\sqrt[3]{-27} = -3",
        "P(A \\mid B) = \\frac{P(B \\mid A)\\,P(A)}{P(B)}",
        "\\mathbb{R}^n \\to \\mathbb{R}^m",
        "\\mathcal{F} = \\mathfrak{g} \\circ \\mathfrak{h}"
      ]
    },
    {
      "Display math",
      "display: true — the multi-line art: stacked fractions, limits under operators,",
      [display: true],
      [
        "\\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}",
        "\\frac{1}{1 + \\frac{1}{1 + \\frac{1}{x}}}",
        "\\sqrt[3]{\\frac{x + 1}{y - 1}}",
        "\\sum_{i=0}^{n} x_i^2",
        "\\prod_{k=1}^{n} k = n!",
        "\\int_{-\\infty}^{\\infty} e^{-x^2}\\,dx = \\sqrt{\\pi}",
        "\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1",
        "\\frac{\\partial^2 u}{\\partial t^2} = c^2 \\nabla^2 u",
        "\\binom{n}{k} = \\frac{n!}{k!\\,(n-k)!}",
        "\\boxed{E = mc^2}"
      ]
    },
    {
      "Delimiters",
      "display: true — `\\left` … `\\right` grows with what it wraps, and the size",
      [display: true],
      [
        "\\left(\\frac{a}{b}\\right)^n",
        "\\left[\\begin{matrix} 1 & 2 \\\\ 3 & 4 \\end{matrix}\\right]",
        "\\left\\{ \\frac{a}{b} \\right\\}",
        "\\left. \\frac{dy}{dx} \\right|_{x=0}",
        "\\frac{d}{dx}\\left( \\int_{a}^{x} f(t)\\,dt \\right) = f(x)",
        "\\big( x \\big) \\quad \\Big[ y \\Big] \\quad \\bigg\\{ z \\bigg\\}"
      ]
    },
    {
      "Matrices, cases and aligned systems",
      "display: true — environments, rows split on `\\\\`, columns on `&`.",
      [display: true],
      [
        "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}",
        "\\begin{bmatrix} 1 & 0 \\\\ 0 & 1 \\end{bmatrix}",
        "\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix} = ad - bc",
        "\\begin{cases} x^2 & x > 0 \\\\ 0 & x \\le 0 \\end{cases}",
        "\\begin{aligned} (a+b)^2 &= a^2 + 2ab + b^2 \\\\ (a-b)^2 &= a^2 - 2ab + b^2 \\end{aligned}"
      ]
    },
    {
      "Braces, stacks and rules",
      "display: true — the three structural commands, and a rule across an array.",
      [display: true],
      [
        "\\overbrace{a + b + \\cdots + z}^{26}",
        "\\underbrace{x \\cdot x \\cdots x}_{n}",
        "\\sum_{\\substack{i=0 \\\\ j=0}}^{n} a_{ij}",
        "\\begin{array}{cc} 1 & 2 \\\\ \\hline 3 & 4 \\end{array}",
        "\\begin{pmatrix} 1 & 2 \\\\ \\hline 3 & 4 \\end{pmatrix}"
      ]
    },
    {
      "The alphabets",
      "The letterlike codepoints only: a letter with none keeps its own.",
      [],
      [
        "\\mathbb{R}, \\mathbb{C}, \\mathbb{Z}",
        "\\mathcal{F}, \\mathcal{L}(V), \\mathcal{H}",
        "\\mathfrak{g}, \\mathfrak{sl}_2, \\mathfrak{C}",
        "\\mathscr{L}, \\mathcal{o}, \\mathcal{e}",
        "\\mathcal{A}, \\mathcal{P}(X)"
      ]
    },
    {
      "What it gives up on",
      "Unsupported or malformed syntax returns nil, and the caller keeps the source.",
      [],
      [
        "\\color{red}{x}",
        "\\cancel{x}",
        "\\hspace{1em} x",
        "\\begin{unknown} x \\end{unknown}",
        "\\frac{1}{"
      ]
    }
  ]

  @unsupported "(unsupported — the caller keeps the source, as pi does)"

  def write(path \\ Path.join(__DIR__, "rendering.txt")) do
    File.write!(path, report())
    IO.puts("wrote #{path}")
  end

  defp report do
    [header() | Enum.map(@sections, &section/1)]
    |> Enum.join("\n")
    |> String.replace(~r/\n{3,}/, "\n\n")
  end

  defp header do
    """
    LatexUnicode — formulas rendered to text
    #{String.duplicate("=", @width)}

    Generated by `mix run examples/render.exs`. Under each source line is what
    LatexUnicode.render/2 returned for it; display math is the multi-line art, and
    inline math is the one line pi renders.
    """
  end

  defp section({title, note, options, formulas}) do
    """
    #{String.duplicate("-", @width)}
    #{title}
    #{String.duplicate("-", @width)}
    #{note}
    """ <> Enum.map_join(formulas, "\n", &example(&1, options))
  end

  defp example(source, options) do
    rendered = LatexUnicode.render(source, options)

    "#{source}\n#{body(rendered)}\n"
  end

  defp body(nil), do: "    #{@unsupported}"

  defp body(rendered) do
    rendered
    |> String.split("\n")
    |> Enum.map_join("\n", &("    " <> &1))
  end
end

RenderingExamples.write()
